/* Generated By:JavaCC: Do not edit this line. CtlParserConstants.java */
package modelCheckCTL.controller.ctl.ctlParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CtlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ATOM = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<ATOM>",
  };

}
